### ISSUE TITLE
Files missing: xprintf.h, yprintf.h, widget_FFTDisplay.h 

### ISSUE THREAD

**Issue by lmcreek** [psvenkat/sdrdude#1]
Hi there,
I'm trying to evaluate the performance of a SDR on a bare metal board( Arduino due/STM32F407DISCO /STM32F746DISCO) and I found your project.
I tried to guess the contents of the missing files : xprintf.h, yprintf.h, widget_FFTDisplay.h (up to now these are missing) but I wasn't very successful.
Best regards
Miguel

**Comment by psvenkat** [comment]
I have uploaded all missing file
